version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  test_python:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r external/fv3util/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "external/fv3util/requirements_dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip3 install -e external/fv3util
            pytest external/fv3util/tests

  build_default:
    machine:
      docker_layer_caching: true
    environment:
      GCR_IMAGE: us.gcr.io/vcm-ml/fv3gfs-python
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    steps:
      - checkout
      - run:
          name: "save gcloud key for gcsfs"
          command: |
            echo $ENCODED_GCR_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - add_ssh_keys:
          fingerprints:
            - "b6:e7:38:b9:a6:61:ec:f2:27:81:0c:8e:b9:79:41:ca"
      - run:
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update
      - run: 
          name: "Compile model and perform model tests"
          command: |
            bash test_docker.sh
      - gcp-gcr/gcr-auth
      - run: |
          echo "$ENCODED_GCR_KEY" | base64 --decode | docker login --username _json_key --password-stdin https://gcr.io
          if [[ "$CIRCLE_BRANCH" == "master" ]]
          then
              echo "pushing untagged image $GCR_IMAGE"
              docker push $GCR_IMAGE
          fi
          if [[ ! -z "$CIRCLE_TAG" ]]
          then
              echo "pushing tagged image $GCR_IMAGE:$CIRCLE_TAG"
              docker tag $GCR_IMAGE $GCR_IMAGE:$CIRCLE_TAG
              docker push $GCR_IMAGE:$CIRCLE_TAG
          fi

workflows:
  version: 2
  tagged-build:
    jobs:
      - test_python:
          filters:
            tags:
              only: /^v.*/
      - build_default:
          requires:
            - test_python
          filters:
            tags:
              only: /^v.*/
